/* Text to put at the beginning of the generated file. Probably a license. */

#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

typedef struct PL {
  double net;
  double amt;
  double profit;
  double ratio;
} PL;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

 const char *big5_to_utf8(const char *big5) ;

 void free_string(const char *ptr) ;


struct PL get_real_pl_detail_big5(const char *m_type,
                                  const char *stock,
                                  const char *t_type,
                                  const char *bs,
                                  long long qty,
                                  double price,
                                  long long amt,
                                  double c_price,
                                  long long net,
                                  long long fee,
                                  double tax_rate,
                                  const char *s_type,
                                  double fee_rate,
                                  long long min_fee,
                                  double market_price)
;


struct PL get_real_pl_detail_utf8(const char *m_type,
                                  const char *stock,
                                  const char *t_type,
                                  const char *bs,
                                  long long qty,
                                  double price,
                                  long long amt,
                                  double c_price,
                                  long long net,
                                  long long fee,
                                  double tax_rate,
                                  const char *s_type,
                                  double fee_rate,
                                  long long min_fee,
                                  double market_price)
;

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

/* Text to put at the end of the generated file */
